  # Intervalo de raspagem de metricas. O padrao eh a cada 60s
  scrape_interval:  10s 
  # Intervalo para avaliacao de regras. O padrao eh a cada 60s
  evaluation_interval: 10s 
  # scrape_timeout eh definido como o padrao global (10s).

alerting:
  alertmanagers:
  - static_configs: 
    - targets:
    # - alertmanager:9093 

rule_files:
   # - "first_rules.yml"
   # - "second_rules.yml"

# metrics_path defaults to '/metrics' scheme defaults to 'http'. 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['172.17.0.1:9090']