version: '3.7'
services:
  app_crud_api:
    container_name: app_crud_api
    build:
      context: '.'
    image: adsoft/app_crud_api:1.0.0
    volumes:
      - ./crud/node_modules:/home/app/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - "db"
    restart: always
  db:
    container_name: db
    image: mongo:4
    # New sintax for declare ports for docker-compose 3.2 or major
    # https://docs.docker.com/compose/compose-file/#ports
    ports:
      - target: 27017    # container
        published: 27018 # host
        protocol: tcp
        mode: bridge
    volumes:
      - /docker/adsoft/db_crud_api:/data/db
    restart: always
